### ISSUE TITLE
Impossible de lancer le serveur

### ISSUE THREAD

**Issue by Laygendev** [AlexMog/SurvivalMMO#4]
Salut,

Après avoir fait un mvn clean puis mvn install, et mvn package.

Jje tente de lancer le serveur avec la commande : java -cp target/survivalgame-0.0.1-SNAPSHOT.jar survivalgame.server.Server

Je tombe sur une erreur comme quoi il en trouve pas la définition de la classe com/google/gson/GsonBuilder. Même erreur en mettant à jour la version du package vers la dernière : 2.8.5.

L'erreur en question lors de l'éxécution de la commande:

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
        at survivalgame.config.JsonConfiguration.<clinit>(JsonConfiguration.java:12)
        at survivalgame.server.Server.<init>(Server.java:13)
        at survivalgame.server.Server.main(Server.java:19)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more

Vu que c'est le première classe utilisé d'une dépendance, j'ai l'impression que mon maven ne les inclus pas dans le .jar ? Je suis débutant en Java, peut être que ce n'est pas du tout ça.

As-tu une idée ?
Est-ce que tu arrives à lancer le serveur de ton coté ?

PS: Je suis sur windows 10, et je lance la console en tant qu'administrateur

**Comment by AlexMog** [comment]
Bonjour,
C'est normal, le maven du projet n'est pas encore configuré pour lui permettre de créer une assembly (par défaut, il crée une Lib, du coup n'intègre pas les dépendances dans le standalone :))
Pour lancer le projet, tu peux plutôt utiliser la commande:
```mvn exec:java -Dexec.mainClass="survivalgame.server.Server"```

Malheureusement, tu vas devoir faire le test sans aucune garanties de ma part, je n'ai plus touché ce projet depuis très longtemps et je n'ai pas le temps actuellement pour m'y remettre, néanmoins, je serais ravis de t'aider si tu tombes sur des problèmes !
